### PR TITLE
Fix/invasion bars

### LINKED ISSUE #3: Config option to reduce the size of the progress bar
It's quite big compared to the rest of our UI. With 4+ players it would get really cluttered.

### PR DESCRIPTION
**Pull request by SekretOne**
Invasion GuI changes. The GUI has been rescaled to better fit and not overwhelm screen. Cleaner more compact look, for today's modern and on-the-go onslaught. Resolves #3. 

### Add

1. An icon! Because.

### Change

1. Rescaled head and bar to be in-scale with the toolbar.
2. Switched to minimalist approach in borders.
3. Removed %, as unnecessary clutter. 
4. Invasion name is now within the progress bar. Name is `abbreviated` if too long to fit cleanly.

#### Before

*UI Scaled to AUTO unless otherwise specified*

Easy consumed 1/3 of the screen

---
#### After

Even with 4 invasions and the bulky AUTO UI scale, a big improvement.

A more plausible experience, playing on NORMAL UI Scale

### CODE REVIEW

**Comment by democat3457** [comment]
If another mod adds UI elements, such as BetterHUD, Antique Atlas, WAILA/HWYLA, or potion icons, would the location of the invasion HUD still be config-able?

**Comment by SekretOne** [comment]
> If another mod adds UI elements, such as BetterHUD, Antique Atlas, WAILA/HWYLA, or potion icons, would the location of the invasion HUD still be config-able?

There's a very basic top left point and 'card width' config present. Relevant section [here](https://github.com/Rebirth-of-the-Night/onslaught/blob/ef0eb12c982fd69af96ea55f0a3c87a95d5de337/src/main/java/com/codetaylor/mc/onslaught/modules/onslaught/ModuleOnslaughtConfig.java#L24-L49).

**Comment by democat3457** [comment]
I see.

**Comment by CalaMariGold** [comment]
I think I would prefer the white outline on the UI like in the original. Other than that, amazing work!

**Comment by SekretOne** [comment]
> I think I would prefer the white outline on the UI like in the original. Other than that, amazing work!

Yeah I was trimming out a lot of the visual distraction. It saves space, but I think you'll find you wouldn't want it *that* eye drawing once playing.

I'd want to completely rivisit the GUI at a later date.

**Pull request merged**
